# Generated by Django 5.0.6 on 2024-05-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_no', models.IntegerField()),
                ('stu_name', models.CharField(max_length=30)),
                ('stu_class', models.IntegerField()),
                ('stu_address', models.CharField(max_length=300)),
            ],
        ),
    ]
